/**
 * Type definitions for tender data
 * Generated by backend/scraper.py
 */

export interface Tender {
  /** Title of the tender */
  titel: string;
  
  /** Estimated budget or "k.A." if not available */
  budget: string;
  
  /** Location/city of the project */
  ort: string;
  
  /** Deadline for submission */
  frist: string;
  
  /** Trade/craft type (e.g., "Dachdeckerarbeiten") */
  gewerk: string;
  
  /** Brief summary (max 10 words) */
  fazit: string;
  
  /** Original source URL from bund.de */
  source_url: string;
  
  /** Publication date from RSS feed */
  published: string;
  
  /** Timestamp when scraped */
  scraped_at: string;
  
  /** Flag indicating analysis failure */
  error?: boolean;
}

export interface TenderData {
  /** ISO timestamp of last update */
  lastUpdated: string;
  
  /** RSS feed source URL */
  source: string;
  
  /** Number of tenders in this batch */
  count: number;
  
  /** Array of analyzed tenders */
  tenders: Tender[];
}

